### ISSUE TITLE
DG review

### ISSUE THREAD

**Issue by hckim0911** [AY1920S2-CS2103T-W17-1/main#283]
- Intro
    - Very nice, easy to see the map of this document.
- Before the section of implementation, I couldn’t see many updates comparing to AB3’s DG. Did you intend to reuse the components in AB3’s one?
- For the model component, it is quite well drawn with proper splits for three parts of your app.
- For the implementation part, all features are well described in detail, however, I would like to recommend to use a proper UML diagram to help the description.
- I skimmed through your DG, and I found your usual descriptions for features for implementation are composed by which syntax is accepted, how the functionality works, error-handling, how methods and data flows in your app to perform the functionality. This is quite nice because I can see the pattern and it is easy to read. 
- One suggestion I can make here is why you don’t use a label for each differentially recognisable contents?
    - e.g., Instead of writing “The add command allows user to create a new Card in the current Deck. The following syntax is accepted:” extracted from 4.3, you can just put : “accepted syntax” as a label for which expression can be acceptable. 
    - And you can title below paragraphs according to their contents and you can apply the titles as template for explaining other features.
    - I mean you can make your document be able to skim with labels and titles.
    - If so, the document doesn’t look wordy but structured more in my personal opinion.
- Except for these points, I think the DG looks nice. Keep it up!

**Comment by hckim0911** [comment]
I recommend you to have a look at the DG of w17-2. They updated all for the DG's beginning part properly so that the implementation part can be not complicated and not repeated. If there is something you can take and apply to your DG to improve, please do so.

**Comment by ncslzh** [comment]
Thank you for the review! We have incorporated some of your suggestions into our DG.
